# These are supported funding model platforms

github: [alexandre020285]
# Open Collective: https://opencollective.com/
# opencollective: alexandre020285
# Ko-Fi: https://ko-fi.com/
# kofi: alexandre020285
# Tidelift: https://tidelift.com/funding/github/
# tidelift: alexandre020285
# Community Bridge: https://funding.communitybridge.org/
# community_bridge: alexandre020285
# Liberapay: https://liberapay.com/
# liberapay: alexandre020285
# IssueHunt: https://issuehunt.io/
# issuehunt: alexandre020285
# Otechie: https://otechie.com/
# otechie: alexandre020285
# Custom: https://www.buymeacoffee.com/
# custom: https://www.buymeacoffee.com/alexandre020285
